version: "3"

services:
  db:
    container_name: flask-api-db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data:delegated
  api:
    container_name: flask-api
    build: ./api
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db-data:
